[project]
name = "transfusion"
version = "0.1.0"
readme = "README.md"
description = "TransFusion: Transcribing Speech with Multinomial Diffusion"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["transfusion", "wavlm"]
